name: GitHub Actions Demo
run-name: Testing out GitHub Actions with Abstracta Challenge 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Maven
        run: sudo apt-get install maven

      - name: Build and run Selenium tests
        env:
          SAUCELABS_KEY: ${{ secrets.SAUCELABS_KEY }}
        run: mvn clean test

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
