name: Maven Build and Test

on: [push]  # Ejecuta el flujo de trabajo en cada push al repositorio

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
    
    - name: Build and test with Maven
      run: mvn clean test
